# permissions for end users to view passlesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: passless-viewer-role
rules:
- apiGroups:
  - wavesoftware.pl
  resources:
  - passlesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wavesoftware.pl
  resources:
  - passlesses/status
  verbs:
  - get
