
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wavesoftware.pl
  resources:
  - passlesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wavesoftware.pl
  resources:
  - passlesses/finalizers
  verbs:
  - update
- apiGroups:
  - wavesoftware.pl
  resources:
  - passlesses/status
  verbs:
  - get
  - patch
  - update
