apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: passless-operator
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - secrets
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resourceNames:
  - passless-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - wavesoftware.pl
  resources:
  - passlesses
  verbs:
  - get
  - list
  - watch
