apiVersion: apps/v1
kind: Deployment
metadata:
  name: passless-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: passless-operator
  template:
    metadata:
      labels:
        name: passless-operator
    spec:
      serviceAccountName: passless-operator
      containers:
        - name: passless-operator
          image: quay.io/wavesoftware/passless-operator
          command:
          - passless-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "passless-operator"
